apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
  - image: registry.access.redhat.com/ubi8/ubi-minimal:latest
    command:
      - /bin/bash
      - -c
      - "sleep infinity"
    name: demopod
